config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  get 'make_master' =>"home#make_master"

  get 'join_flea/index'
  get 'join_flea/join' =>"join_flea#join"
  post 'make/:flea_id' => "join_flea#make"
  get 'apply/:flea_id' => "join_flea#apply"
  get 'judge_fleas/index'
  get 'judge_fleas/judge/:flea_id' => "judge_fleas#judge"
  get 'judge_fleas/show/:flea_id/:user_id' => "judge_fleas#show"
  post 'confirm_join/:flea_id/:user_id' => "judge_fleas#confirm_join"
  get 'judge_fleas/result/:flea_id/:user_id' => "judge_fleas#result"
  get 'judge_fleas/select_up/:flea_id/:user_id' => "judge_fleas#select_up"
  get 'judge_fleas/select_down/:flea_id/:user_id' => "judge_fleas#select_down"

  get 'mastermenu/user_manage'
  get 'mastermenu/level_up/:user_id' => 'mastermenu#level_up'
  get 'mastermenu/level_down/:user_id' =>"mastermenu#level_down"
  get 'mastermenu/otherinfo/:user_id' =>"info#otherinfo"
  get 'mastermenu/destroy/:user_id' =>"mastermenu#destroy"
  get 'mastermenu/flea_destroy/:flea_id' => "mastermenu#flea_destroy"
  get 'mastermenu/judge/:user_id' => "mastermenu#judge"
  get 'mastermenu/index'
  get 'mastermenu/flea_manage' => "mastermenu#flea_manage"

  get 'mastermenu/write_email/:user_id' => "mastermenu#write_email"
  post 'send_email/:user_id'=>'mastermenu#send_email'

  get 'mastermenu/write_sms/:user_id' =>"mastermenu#write_sms"
  post 'send_sms/:user_id'=>'mastermenu#send_sms'

  get 'mastermenu/write_notice'
  post 'create_notice' =>"mastermenu#create_notice"
  get 'destroy_notice/:notice_id' =>"mastermenu#destroy_notice"
  get 'mastermenu/update_notice/:notice_id' => "mastermenu#update_notice"
  post 'real_update_notice/:notice_id'=>"mastermenu#real_update_notice"

  get 'show_notice/:notice_id' => "mastermenu#show_notice"
  get 'search/search_main'
  get 'user' => "search#user"
  get 'search/flea_application_date'
  get 'search/flea_city_place'
  get 'search/flea_event_date'
  get 'search/planner'
  get 'search/seller'
  get 'item/create'
  post 'create_item' => "item#create_item"
  get 'destroy_item/:item_id' =>"item#destroy"
  get 'update_item/:item_id' => "item#update"
  post 'real_update_item/:item_id'=>"item#real_update"
  get 'item/show'
  get 'production_process/:item_id' => "item#production_process"
  post 'pp_edit/:item_id' => "item#pp_edit"
  get 'pp_edit/:item_id' => "item#pp_edit"
  get 'show_info/:user_id' => "info#show_info"
  get 'info/level_up'
  get 'standby/:user_id' => "info#standby"

  get 'info/add_prize/:user_id' =>"info#add_prize"
  post 'create_prize/:user_id' => "info#create_prize"
  get 'info/add_activity/:user_id' =>"info#add_activity"
  post 'create_activity/:user_id'=>"info#create_activity"

  get 'destroy_activity/:user_id/:activity_id' =>"info#destroy_activity"
  get 'destroy_prize/:user_id/:prize_id' =>"info#destroy_prize"

  resources :fleas do
    member do
      post 'like'
      post 'dislike'
    end
  end

  post 'home/upload'
  get 'home/index'
  get 'home/faq'
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/flea.rb
# 플리마켓
class Flea < ActiveRecord::Base
  has_many :participations
  has_many :users, through: :participations
  belongs_to :user
  has_many :like_flea_markets
  has_many :users, through: :like_flea_markets
  has_many :comment_flea_markets
  has_many :users, through: :comment_flea_markets
  has_many :flea_sellers

  mount_uploader :poster_url, FleaMainUploader

  validates :number_of_recruitment, presence: {message: "인원을 제대로 입력하지 않았습니다."}
  validates :city_place, presence: {message: "개최도시를 제대로 입력하지 않았습니다."}
  validates :detail_place, presence: {message: "상세정보를 제대로 입력하지 않았습니다."}
  validates :entrance_fee, presence: {message: "금액을 제대로 입력하지 않았습니다."}
end

app/controllers/fleas_controller.rb
class FleasController < ApplicationController
  before_action :set_flea, only: [:show, :edit, :update, :destroy, :like, :dislike]
  # GET /fleas
  # GET /fleas.json
  def index
    @search_flea = Array.new
    @option = params[:option]
    if @option.nil?
      if params[:city].nil? && params[:search].nil?
        # 페이지 처음 로딩했을 때
        # .order(:event_end_date)
        fleas = Flea.all
        date = Date.today
        fleas.each do |p|
          if p.event_start_date <= date && date <= p.event_end_date
            @search_flea.append(p)
          end
        end
      else
        # 지역이랑 날짜로 검색
        @search_city = params[:city]
        @search_time = params[:search]
        if @search_time.nil?
          @search_time = Time.now.to_s.to_date
        end

        if @search_city == '전체'
          fleas = Flea.all.order(:event_end_date)
        elsif @search_city == nil
          fleas = Flea.all.order(:event_end_date)
        else
          fleas = Flea.where(city_place: @search_city).order(:event_end_date)
        end

        date = @search_time.to_s.to_date
        unless fleas.nil?
          fleas.each do |p|
            if p.event_start_date <= date && date <= p.event_end_date
              @search_flea.append(p)
            end
          end
        end
      end
    else
      # 과거 현재 미래 검색
      fleas = Flea.all.order(:event_end_date)
      date = Date.today

      if @option == 'now'
        fleas.each do |p|
          if p.event_start_date <= date && date <= p.event_end_date
            @search_flea.append(p)
          end
        end
        @title_ko = '오늘의 마켓'
        @title_eng = 'TODAY MARKET'
      elsif @option == 'future'
        fleas.each do |p|
          if date <= p.event_start_date
            @search_flea.append(p)
          end
        end
        @title_ko = '내일의 마켓'
        @title_eng = 'ONCOMING MARKET'
      elsif @option == 'past'
        fleas.each do |p|
          if p.event_end_date <= date
            @search_flea.append(p)
          end
        end
        @title_ko = '어제의 마켓'
        @title_eng = 'FINISHED MARKET'
      end
    end
    count = @search_flea.count
    if count >= 4
      @recently_flea = @search_flea.take(4)
    else
      @recently_flea = @search_flea.take(count)
    end
  end

  def show
    @has_like = @flea.like_flea_markets.where(flea_id: @flea.id, user_id: current_user.id).blank? if current_user
    @user = User.find(@flea.user_id)
  end

  def like
    if current_user && LikeFleaMarket.create(flea_id: @flea.id, user_id: current_user.id)
      redirect_to @flea
    else
      render :show, notice: 'Like fail'
    end
  end

  def dislike
    if current_user && LikeFleaMarket.find_by(flea_id: @flea.id, user_id: current_user.id).destroy
      redirect_to @flea
    else
      render :show, notice: 'Like success'
    end
  end

  def new
    @flea = Flea.new
  end

  # GET /fleas/1/edit
  def edit
  end

  # POST /fleas
  # POST /fleas.json
  def create
    @flea = Flea.new(flea_params)
    @flea.user_id = current_user.id

    if @flea.save
      redirect_to @flea, notice: 'post was successfully created'
    else
      render :new
    end
  end

  # PATCH/PUT /fleas/1
  # PATCH/PUT /fleas/1.json
  def update
    if @flea.update(flea_params)
      redirect_to @flea, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /fleas/1
  # DELETE /fleas/1.json
  def destroy
    @flea.destroy
    redirect_to '/'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_flea
    @flea = Flea.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def flea_params
    params.require(:flea).permit(:name, :application_start_date, :application_end_date, :number_of_recruitment, :remark, :city_place, :detail_place, :event_start_date, :event_end_date, :entrance_fee, :user_id, :join_type, :item_count, :agree1, :agree2, :agree3, :agree4, :agree5, :poster_url)
  end
end

app/helpers/fleas_helper.rb
module FleasHelper
  def likeBtn(hasLike)
    if hasLike.nil?
        link_to 'Log IN!', new_user_session_path
    elsif hasLike
      link_to like_flea_path(@flea), method: :post do
        content_tag :i, nil, class: 'fa fa-thumbs-o-up', 'aria-hidden' => 'true'
      end
    else
      link_to dislike_flea_path(@flea), method: :post do
        content_tag :i, nil, class: 'fa fa-thumbs-o-down', 'aria-hidden' => 'true'
      end
    end
  end
end

app/views/fleas/_form.html.erb
<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h4 class="text-uppercase">마켓등록하기</h4>
        <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li class="active">마켓등록하기</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<div class="wrapper">
  <div class="container">
    <div class="career-form ">
      <div class="page-content text-center">
        <%= form_for(@flea) do |f| %>
            <% if @flea.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@flea.errors.count, 'error') %>
                    prohibited this flea from being saved:</h2>
                  <ul>
                    <% @flea.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <div class="heading-title text-center">
              <h3 class="text-uppercase" style ="font-weight:bold;">Apply Now
              </h3>
              <span class="text-uppercase">마켓 지원하기</span>
            </div>
            <div class="divider divider-small d-solid d-single text-center">
              <span class="dot"></span>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-10">
              <div class="heading-title-alt text-center">
                <h3 class="text-uppercase">기본정보</h3>
                <span class="text-uppercase">자세히 입력 해주세요!</span>
              </div>
              <br>
              <div class="form-group col-md-6">
                <%= f.label :'플리마켓 시작일시' %><br>
                <%= f.date_select :event_start_date, :class => 'form-control' %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'플리마켓 종료일시' %><br>
                <%= f.date_select :event_end_date, :class => 'form-control' %>
              </div>
              <br>
              <div class="form-group col-md-6">
                <%= f.label :'플리마켓 명' %><br/>
                <%= f.text_field :name, :class => 'form-control', :placeholder => '예)서울 밤도깨비 야시장' %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'지역' %>
                <%= f.select(:city_place,
                             ['서울', '인천', '대전', '대구', '부산', '광주', '울산',
                              '경기', '충남', '충북', '전남', '전북', '경남', '경북', '제주'], {}, {:class => 'form-control'}) %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'상세_주소' %><br>
                <%= f.text_field :detail_place, :class => 'form-control', :placeholder => '예)서울 여의도, DDP, 목동운동장, 청계광장' %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'플리마켓 설명' %><br>
                <%= f.text_field :remark, :class => 'form-control', :placeholder => '예)신나는 공연과 핸드메이드 상품, 푸짐하게 펼쳐진 세계 각국의 음식들을 한 곳에서!' %>
              </div>
              <div class="heading-title-alt text-center">
                <h3 class="text-uppercase">모집정보</h3>
                <span class="text-uppercase">자세히 입력 해주세요!</span>
              </div>
              <br>
              <div class="form-group col-md-6">
                <%= f.label :'접수 시작일시' %><br>
                <%= f.date_select :application_start_date, :class => 'form-control' %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'접수 종료일시' %><br>
                <%= f.date_select :application_end_date %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'모집방식' %>
                <%= f.select(:join_type, ['선착순', '심사'], {}, {:class => 'form-control'}) %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'모집 인원' %><br>
                <%= f.number_field :number_of_recruitment, :class => 'form-control', min: '0', placeholder: '숫자를 입력하여 주세요' %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'참가비' %><br>
                <%= f.number_field :entrance_fee, :class => 'form-control', min: '0', step: '100', placeholder: '100원 단위에요' %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label :'최대 지원가능한 아이템' %><br>
                <%= f.number_field :item_count, :class => 'form-control', min: '0', max: '5', placeholder: '최대 5개에요' %>
              </div>
              <div class="heading-title-alt text-center">
                <h3 class="text-uppercase">동의사항 입력</h3>
                <span class="text-uppercase">더 이상 없을 경우 입력하지 마세요!</span>
              </div>
              <br>
              <dl class="toggle time-line">
                <dt>
                  <a href="">1번째 동의사항</a>
                </dt>
                <dd>
                  <%= f.text_field :agree1, :class => 'form-control', :value => '본인은 작성한 위 사항에 틀림이 없으며, 개인정보 수집 및 이용에 동의합니다.' %>
                </dd>
                <dt>
                  <a href="">2번째 동의사항</a>
                </dt>
                <dd>
                  <%= f.text_field :agree2, :class => 'form-control', :value => '본인은 행사에 참여함에 있어 개장 및 폐장 시간을 엄격하게 준수합니다.' %>
                </dd>
                <dt>
                  <a href="">3번째 동의사항</a>
                </dt>
                <dd>
                  <%= f.text_field :agree3, :class => 'form-control', :value => '본인은 주최 측에서 제공하는 물품의 유지 및 보안의 책임을 갖고 운영할 것이며, 행사 후 청결 상태 유지에 노력합니다.' %>
                </dd>
                <dt>
                  <a href="">4번째 동의사항</a>
                </dt>
                <dd>
                  <%= f.text_field :agree4, :class => 'form-control' %>
                </dd>
                <dt>
                  <a href="">5번째 동의사항</a>
                </dt>
                <dd>
                  <%= f.text_field :agree5, :class => 'form-control' %>
                </dd>
              </dl>
              <br>
              <div class="heading-title-alt text-center">
                <h3 class="text-uppercase">마켓대표이미지</h3>
                <span class="text-uppercase">마켓을 잘 나타내주는 사진을 올려주세요</span>
              </div>
              <br>
              <div class="form-group">
                <%= f.file_field :poster_url, :class => 'form-control' %>
              </div>
            </div>

            <br>
            <div class="actions form-group text-center m-top-30 inline-block">
              <%= f.submit '마켓 등록하기', :class => 'btn btn-medium  btn-theme-color btn-rounded' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fleas/edit.html.erb
<h1>Editing Flea</h1>

<%= render 'form' %>
<%= link_to 'Show', @flea %> |
<%= link_to 'Back', fleas_path %>

app/views/fleas/index.html.erb
<section class="page-title">
    <div class="container">
        <% if @option.nil? %>
        <h4 id="title_eng" class="text-uppercase">Today's market</h4>
        <ol class="breadcrumb">
            <li>
                <a href="/">Home</a>
            </li>
            <li id="title_ko" class="active">오늘의 마켓</li>
        </ol>
    <% else %>
        <h4 id="title_eng" class="text-uppercase"><%= @title_eng %></h4>
        <ol class="breadcrumb">
            <li>
                <a href="/">Home</a>
            </li>
            <li id="title_ko" class="active"><%= @title_ko %></li>
        </ol>
        <% end %>
    </div>
</section>
<section class="body-content page-content">
    <div class="container">
        <div class="heading-title text-center">
            <h3 class="text-uppercase" style="font-weight:bold;">Open Market</h3>
            <span class="text-uppercase">클릭해서 정보를 확인해보세요!</span>
            <form style = "text-center">
                <div class="inline-group">
                    <input type="radio" name="city" checked="true" value="전체"/>전체<input type="radio" name="city" value="서울"/>서울
                    <input type="radio" name="city" value="인천"/>인천
                    <input type="radio" name="city" value="대전"/>대전
                    <input type="radio" name="city" value="대구"/>대구
                    <input type="radio" name="city" value="부산"/>부산
                    <input type="radio" name="city" value="광주"/>광주
                    <input type="radio" name="city" value="울산"/>울산
                    <input type="radio" name="city" value="경기"/>경기
                    <input type="radio" name="city" value="충남"/>충남
                    <input type="radio" name="city" value="충북"/>충북
                    <input type="radio" name="city" value="전남"/>전남
                    <input type="radio" name="city" value="전북"/>전북
                    <input type="radio" name="city" value="경남"/>경남
                    <input type="radio" name="city" value="경북"/>경북
                    <input type="radio" name="city" value="제주"/>제주
                    <span> | </span>
                    <% if @search_time.nil? %>
                      <%= date_field_tag(:search, :date, value: Date.today.to_s) %>
                    <% else %>
                      <%= date_field_tag(:search, :date, value: @search_time) %>
                    <% end %>
                    <span> | </span>
                    <button type="submit" id="searchbtn" class="btn">해당조건으로 검색</button>
                </div>
                <div class="input-group-btn">
                    <button class="btn" type="submit" name="option" value="future" id="future_fleas">진행예정</button>
                    <button class="btn" type="submit" name="option" value="now" id="now_fleas">진행중</button>
                    <button class="btn" type="submit" name="option" value="past" id="past_fleas">종료</button>
                </div>
            </form>
        </div>
        <div class="row">
            <% unless @recently_flea.nil? %>
            <% @recently_flea.each do |h| %>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="team-member">
                    <div class="team-img2">
                      <%= image_tag h.poster_url %>
                        <div class="team-intro light-txt">
                          <h5><%= h.name %></h5>
                          <span><%= h.city_place %></span>
                        </div>
                    </div>
                    <br>
                    <div class="team-hover">
                        <div class="desk">
                            <br>
                            <h4><%= h.name %></h4>
                            <p>
                                <%= h.city_place %>시<br>
                                <%= h.detail_place %>
                            </p>
                        </div>
                        <div class="s-link">
                            <a class="btn btn-extra-small btn-circle btn-dark-border" href="/fleas/<%=h.id%>">
                                보러가기
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
          <% end %>
        </div>
        <div class="divider divider-small d-solid d-single text-center">
            <span class="dot"></span>
        </div>
      </div>



        <div class="container">
          <div class="heading-title text-center">
              <h3 class="text-uppercase" style="font-weight:bold;">Market list</h3>
              <span class="text-uppercase">클릭해서 정보를 확인해보세요!</span>
            </div>
            <div class="row">
            <% unless @search_flea.nil? %>
              <% @search_flea.each do |f| %>
              <div class="col-md-4 col-sm-6 col-xs-12">
                  <div class="team-member">
                      <div class="team-img">
                          <%= image_tag f.poster_url%>
                          <div class="team-intro light-txt">
                              <h5><%= f.name %></h5>
                              <span><%= f.city_place %></span>
                          </div>
                          <br>
                      </div>
                      <br>
                      <div class="team-hover">
                          <div class="desk">
                              <br><br>
                              <h4><%= f.name %></h4>
                              <p>
                                  모집시작날짜 :
                                  <%= f.application_start_date %><br>
                                  모집종료날짜 :
                                  <%= f.application_end_date %><br>
                                  행사시작날짜 :
                                  <%= f.event_start_date %><br>
                                  행사종료날짜 :
                                  <%= f.event_end_date %><br><br>
                                  상세장소 :
                                  <%=f.city_place%> / <%= f.detail_place %><br>
                                  현재지원 :
                                  <%= f.join_member %>명
                                  비고 :
                                  <%=f.remark%>
                              </p>
                          </div>
                          <div class="s-link">
                              <a class="btn btn-extra-small btn-circle btn-dark-border" href="/fleas/<%= f.id %>" class="confirmation">
                                  보러가기
                              </a>
                          </div>
                      </div>
                  </div>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>
    </div>
</section>

<script>

$(document).ready(function () {

    $('input[type=date]').css({"line-height": "20px", "margin-top": "10px"});
    $('.labels').css({"margin": "8px 2px 0px", "font-weight": "bold"});
    $('.inline-group').css({"padding": "20px 0px"});
    $('.postersImage').css({"margin-right": "18px"});
    $('.btn').css({"background-color": "#fff", "border": "1px solid black"});

    $("#now_fleas").click(function () {
        $("#title_eng").val("Today market");
        $("#title_ko").val("오늘의 마켓");
    });
    $("#past_fleas").click(function () {
        $("#title_eng").val("Finished market");
        $("#title_ko").val("어제의 마켓");
    });
    $("#future_fleas").click(function () {
        $("#title_eng").val("Oncoming market");
        $("#title_ko").val("내일의 마켓");
    });
});
</script>

app/views/fleas/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
<%= render 'form' %>
</body>
</html>

app/views/fleas/show.html.erb
<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h4 class="text-uppercase">마켓보기</h4>
        <ol class="breadcrumb">
          <li>
            <a>오늘의마켓</a>
          </li>
          <li class="active">
            <a>마켓정보</a>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>
<section class="body-content page-content">
  <div class="container">
    <div class="row">
      <!--post style 3 start-->
      <div class="post-list-aside">
        <div class="post-single">
          <div class="col-md-5">
            <div class="post-img title-img">
              <%= image_tag @flea.poster_url %>
            </div>
          </div>
          <div class="col-md-7">
            <div class="post-desk">
              <div class="heading-title-alt text-left">
                <h2 class="text-uppercase"><%= @flea.name %></h2>
                <span><%= @user.email %> / <a href="show_info/<%= @user.id %>"><%= @user.nickname %></a></span>
                <br><br><br>
              </div>
              <table class="table">
                <thead>
                <tr>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <th scope="row" style="width:30%">모집기간</th>
                  <td><%= @flea.application_start_date %>~<%= @flea.application_end_date %></td>
                </tr>
                <tr>
                  <th scope="row">행사기간</th>
                  <td><%= @flea.event_start_date %>~<%= @flea.event_end_date %></td>
                </tr>
                <tr>
                  <th scope="row">모집인원</th>
                  <td><%= @flea.number_of_recruitment %></td>
                </tr>
                <tr>
                  <th scope="row">장소</th>
                  <td><%= @flea.city_place %> <%= @flea.detail_place %></td>
                </tr>
                <tr>
                  <th scope="row">참가비</th>
                  <td><%= @flea.entrance_fee %></td>
                </tr>
                <tr>
                  <th scope="row">비고</th>
                  <td><%= @flea.remark %></td>
                </tr>
                </tbody>
              </table>

              <div class="container">
                <div class="row">
                  <div class="count-down-alt light-bg circle">
                    <div class="clock"></div>
                  </div>
                </div>
              </div>
              <br><br>
              <h4>
                <%= "좋아요! #{@flea.like_flea_markets.count}개" %>
                <div class="btn btn-extra-small btn-dark-border"><%= likeBtn(@has_like) %></div>
                <div class="btn btn-extra-small btn-dark-border"><%= link_to '뒤로가기', fleas_path %></div>
                <% if current_user.id == @flea.user_id %>
                    <div class="btn btn-extra-small btn-dark-border"><%= link_to '수정하기', edit_flea_path(@flea) %></div>
                <% end %>
              </h4>
            </div>
          </div>
        </div>
      </div>
      <!--post style 3 end-->
    </div>


  </div>
</section>

<script>
  $('.clock').countdown('<%= @flea.application_end_date %>', function (event) {
    var $this = $(this).html(event.strftime(''
//                 + '<span>%w</span> weeks '
        + '<span class="c-grid"> <span class="c-value">%D</span> <span class="c-title"><br>days</span> </span> '
        + '<span class="c-grid"> <span class="c-value">%H</span> <span class="c-title"><br>hours</span> </span> '
        + '<span class="c-grid"> <span class="c-value">%M</span> <span class="c-title"><br>minutes</span> </span> '
        + '<span class="c-grid"> <span class="c-value">%S</span> <span class="c-title"><br>seconds</span> </span> '));
    $('.count-down .c-grid, .count-down-alt .c-grid').css({"margin": "0px 0px"});
  });

</script>